In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
!wget https://www.dropbox.com/s/fxn3ldztzwxm0rw/FruitsData.zip

--2024-12-14 07:44:37--  https://www.dropbox.com/s/fxn3ldztzwxm0rw/FruitsData.zip
Resolving www.dropbox.com (www.dropbox.com)... 162.125.80.18, 2620:100:6031:18::a27d:5112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.80.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.dropbox.com/scl/fi/9yk0lswtlos77qol2lczt/FruitsData.zip?rlkey=h93ccjqueouw9ealvhrqjd39r [following]
--2024-12-14 07:44:37--  https://www.dropbox.com/scl/fi/9yk0lswtlos77qol2lczt/FruitsData.zip?rlkey=h93ccjqueouw9ealvhrqjd39r
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://uc234be119804b9d0e920892ff60.dl.dropboxusercontent.com/cd/0/inline/CgN64YMOu8D-hoP-ScBY2y7N_m0rpK7oLhsKK7pEozE4M4BJV8C8zJQTf4LdpAhzf5PDn4fbTz9jUpYj-tBS-lmn7aTTuCEaqLEu7iZT2S_Llaw03qRvKY_QiGbrAw_oaOgUWKMiJrDlp8ZK37Fn4zY3/file# [following]
--2024-12-14 07:44:38--  https://uc234be119804b9d0e920892ff60.dl.dropboxusercontent.com/cd/0

In [6]:
!unzip -q "/content/FruitsData.zip"

In [7]:
# Imports required for this project
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

tf.random.set_seed(4)

In [8]:
# Creating the Pathlib PATH objects
train_path = Path("fruits-360/Training")
test_path = Path("fruits-360/Test")

In [9]:
# Getting Image paths
train_image_paths = list(train_path.glob("*/*"))
train_image_paths = list(map(lambda x : str(x) , train_image_paths))

train_image_paths[:10]

['fruits-360/Training/Plum 2/r_148_100.jpg',
 'fruits-360/Training/Plum 2/r_250_100.jpg',
 'fruits-360/Training/Plum 2/r_273_100.jpg',
 'fruits-360/Training/Plum 2/266_100.jpg',
 'fruits-360/Training/Plum 2/202_100.jpg',
 'fruits-360/Training/Plum 2/r_3_100.jpg',
 'fruits-360/Training/Plum 2/243_100.jpg',
 'fruits-360/Training/Plum 2/r_178_100.jpg',
 'fruits-360/Training/Plum 2/r_117_100.jpg',
 'fruits-360/Training/Plum 2/36_100.jpg']

In [10]:
# Getting their respective labels

def get_label(image_path):
    return image_path.split("/")[-2]

train_image_labels = list(map(lambda x : get_label(x) , train_image_paths))
train_image_labels[:10]

['Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2',
 'Plum 2']

In [11]:
from sklearn.preprocessing import LabelEncoder

Le = LabelEncoder()
train_image_labels = Le.fit_transform(train_image_labels)

train_image_labels[:10]

array([103, 103, 103, 103, 103, 103, 103, 103, 103, 103])

In [12]:
train_image_labels = tf.keras.utils.to_categorical(train_image_labels)

train_image_labels[:10]

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [13]:
from sklearn.model_selection import train_test_split

Train_paths , Val_paths , Train_labels , Val_labels = train_test_split(train_image_paths , train_image_labels)

In [14]:
Train_paths[:10] , Train_labels[:10]

(['fruits-360/Training/Dates/r_261_100.jpg',
  'fruits-360/Training/Maracuja/319_100.jpg',
  'fruits-360/Training/Carambula/r_74_100.jpg',
  'fruits-360/Training/Cucumber Ripe/15_100.jpg',
  'fruits-360/Training/Potato Red/0_100.jpg',
  'fruits-360/Training/Cherry Wax Red/r_166_100.jpg',
  'fruits-360/Training/Grape White 2/r_6_100.jpg',
  'fruits-360/Training/Pomegranate/r_201_100.jpg',
  'fruits-360/Training/Pepper Yellow/r_54_100.jpg',
  'fruits-360/Training/Quince/191_100.jpg'],
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [15]:
# Function used for Transformation

def load(image , label):
    image = tf.io.read_file(image)
    image = tf.io.decode_jpeg(image , channels = 3)
    return image , label

In [17]:
!pip install --upgrade tensorflow

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 615.3/615.3 MB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 95.9 MB/s eta 0:00:00
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.17.1
    Uninstalling tensorboard-2.17.1:
      Successfully uninstalled tensorboard-2.17.1
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.17.1
    Uninstalling tensorflow-2.17.1:
      Successfully uninstalled tensorflow-2.17.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tf-keras 2.17.0 requires tensorflow<2.18,>=2.17, but you have tensorflow 2.18.0 which is incompatible.


In [3]:
!pip install tensorflow==2.13

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 524.1/524.1 MB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 65.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.3/17.3 MB 87.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 95.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 27.0 MB/s eta 0:00:00
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.12.2
    Uninstalling typing_extensions-4.12.2:
      Successfully uninstalled typing_extensions-4.12.2
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  Attempting uninstall: keras
    Found existing installation: keras 3.5.0
    Uninstalling keras-3.5.0:
      Successfully uninstalled keras-3.5.0
  Attempting uninstall: gast
    Found existing installation: gast 0.6.0
    Uninstalling gast-0.6.0:
      

In [3]:
from tensorflow.keras.layers.preprocessing import Resizing

import tensorflow as tf

# Define IMAGE SIZE and BATCH SIZE
IMG_SIZE = 224
BATCH_SIZE = 32

# Basic Transformation
resize = tf.keras.Sequential([
    Resizing(IMG_SIZE, IMG_SIZE)
])

# Data Augmentation
data_augmentation = tf.keras.Sequential([
    tf.keras.layers.experimental.preprocessing.RandomFlip("horizontal"),
    tf.keras.layers.experimental.preprocessing.RandomRotation(0.2),
    tf.keras.layers.experimental.preprocessing.RandomZoom(height_factor = (-0.3, -0.2))
])

ModuleNotFoundError: No module named 'tensorflow.keras.layers.preprocessing'