In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [4]:
dataset=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/indian_liver_patient.csv')

In [47]:
dataset.isnull().sum()

Age                           0
Gender                        0
Total_Bilirubin               0
Direct_Bilirubin              0
Alkaline_Phosphotase          0
Alamine_Aminotransferase      0
Aspartate_Aminotransferase    0
Total_Protiens                0
Albumin                       0
Albumin_and_Globulin_Ratio    4
Dataset                       0
dtype: int64

In [49]:
dataset.dropna(inplace=True)

In [50]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [51]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))


In [52]:
x

array([[1.0, 0.0, 65, ..., 6.8, 3.3, 0.9],
       [0.0, 1.0, 62, ..., 7.5, 3.2, 0.74],
       [0.0, 1.0, 62, ..., 7.0, 3.3, 0.89],
       ...,
       [0.0, 1.0, 52, ..., 6.4, 3.2, 1.0],
       [0.0, 1.0, 31, ..., 6.8, 3.4, 1.0],
       [0.0, 1.0, 38, ..., 7.3, 4.4, 1.5]], dtype=object)

In [53]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)
x


array([[ 1.77079482, -1.77079482,  1.24740264, ...,  0.29372174,
         0.20344649, -0.14738974],
       [-0.56471817,  0.56471817,  1.06230624, ...,  0.93965456,
         0.07746198, -0.64846078],
       [-0.56471817,  0.56471817,  1.06230624, ...,  0.47827397,
         0.20344649, -0.17870668],
       ...,
       [-0.56471817,  0.56471817,  0.44531827, ..., -0.07538274,
         0.07746198,  0.16577966],
       [-0.56471817,  0.56471817, -0.85035649, ...,  0.29372174,
         0.329431  ,  0.16577966],
       [-0.56471817,  0.56471817, -0.4184649 , ...,  0.75510233,
         1.5892761 ,  1.73162664]])

In [103]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


[1.7707948175083101,
 -1.7707948175083101,
 -0.912055285164517,
 -0.4203198419206351,
 -0.4598783773365404,
 -0.9384211821868875,
 -0.2738762049306863,
 -0.2880338953613061,
 -0.6290394423553506,
 0.3294309986434161,
 1.4184572451730044]

In [117]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
x_train = imputer.fit_transform(x_train)
x_test = imputer.transform(x_test)



In [88]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)


LogisticRegression(random_state=0)

In [116]:
y_pred = classifier.predict(x_test)

In [90]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")


Accuracy: 0.7241379310344828
Precision: 0.7314814814814815
Recall: 0.9634146341463414


array([2])

In [79]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(random_state=0)
classifier.fit(x_train,y_train)

DecisionTreeClassifier(random_state=0)

In [80]:
y_pred = classifier.predict(x_test)

In [81]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")


Accuracy: 0.6379310344827587
Precision: 0.7325581395348837
Recall: 0.7682926829268293


In [82]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)  # Adjust n_neighbors
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [83]:
y_pred = classifier.predict(x_test)

In [84]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")


Accuracy: 0.6293103448275862
Precision: 0.7241379310344828
Recall: 0.7682926829268293


In [85]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train, y_train)

GaussianNB()

In [86]:
y_pred = classifier.predict(x_test)

In [87]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")


Accuracy: 0.5431034482758621
Precision: 0.9393939393939394
Recall: 0.3780487804878049
