In [1]:
import statistics as st


In [5]:
age =[20,19,20,18,21,22]
m_age=st.mean(age)
me_age=st.median(age)
mo_age=st.mode(age)
print("mean age :",m_age,"\nmedian age :",me_age,"\nmode age :",mo_age)

mean age : 20 
median age : 20.0 
mode age : 20


In [9]:
age =[20,19,20,18,21,22,20]
va_age=st.variance(age)
sd_age=st.stdev(age)
print("variance age :",va_age,"\nstandard deviation age :",sd_age)

variance age : 1.6666666666666667 
standard deviation age : 1.2909944487358056


In [8]:
age=[20,19,20,18,21,22,20]
r_age=max(age)-min(age)
print("range age :",r_age)

range age : 4


In [13]:
l1=[1,2]
l2=[2,4]
print(l1+l2)

[1, 2, 2, 4]


In [17]:
print(l1+3)

TypeError: can only concatenate list (not "int") to list

In [18]:
!pip install numpy

In [19]:
import numpy as np

In [20]:
a1=np.array(20)
print(a1)
print('Dim ',a1.ndim)

20
Dim  0


In [21]:
a2=np.array([10,20,30,10,30,405,505,50,50])
print(a2)
print('Dim ',a2.ndim)

[ 10  20  30  10  30 405 505  50  50]
Dim  1


In [22]:
a3=np.array([[10,20,30],[10,30,405],[505,50,50]])
print(a3)
print('Dim ',a3.ndim)

[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
Dim  2


In [25]:
a4=np.array([[[[10]]]])
print(a4)
print('Dim ',a4.ndim)

[[[[10]]]]
Dim  4


In [31]:
a3=np.array([[10,20,30],[10,30,405],[505,50,50]],dtype=np.int64)
print(a3)
print('Dim ',a3.ndim)
print('Shape :',a3.shape)
print('Size: ',a3.size)
print('Item Size : ',a3.itemsize)
print('Data Type : ',a3.dtype)


[[ 10  20  30]
 [ 10  30 405]
 [505  50  50]]
Dim  2
Shape : (3, 3)
Size:  9
Item Size :  8
Data Type :  int64


In [32]:
a4=np.array([505,50,50,40])
print('Shape :',a4.shape)
print('Size : ',a4.size)

Shape : (4,)
Size :  4


In [35]:
a5=np.empty((5,5))
a5

array([[4.89473010e-310, 0.00000000e+000, 4.95593417e-062,
        8.74496193e-322, 6.88019006e-310],
       [6.88019006e-310, 1.35617292e+248, 9.46215455e-053,
        4.21912751e-090, 6.09987498e+170],
       [1.56088502e+184, 1.69177025e-052, 4.99874558e+217,
        5.49419094e-143, 2.21211602e+214],
       [5.22411352e+257, 1.11475752e+261, 1.16318408e-028,
        1.04914792e-153, 1.94918966e-153],
       [9.72159846e-072, 2.26166164e-076, 1.25625009e-071,
        6.14895646e-154, 1.10670705e-321]])

In [34]:
from re import A
a5=np.zeros((3,5))
a5


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
a6=np.ones((4,4))
a6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
a7=np.arange(2,101,2)
a7

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [45]:
a8=np.reshape(a7,(5,10))
a8

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [55]:
a1=np.arange(10)
a2=np.arange(11,21)
print(a1,a2)

[0 1 2 3 4 5 6 7 8 9] [11 12 13 14 15 16 17 18 19 20]


In [49]:
print(a1+2)
print(a1*2)
print(a1/2)
print(a1**2)


[ 2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[ 0  1  4  9 16 25 36 49 64 81]


In [56]:
print(a1+a2)
print(a1*a2)
print(a1/a2)
print(a1**a2)

[11 13 15 17 19 21 23 25 27 29]
[  0  12  26  42  60  80 102 126 152 180]
[0.         0.08333333 0.15384615 0.21428571 0.26666667 0.3125
 0.35294118 0.38888889 0.42105263 0.45      ]
[                   0                    1                 8192
              4782969           1073741824         152587890625
       16926659444736     1628413597910449   144115188075855872
 -6289078614652622815]


In [53]:
print(np.random.rand())
print(np.random.randn())
print(np.random.rand(10,100,10))


0.1813241290668708
-0.99760625446473
[[[0.65782732 0.7822288  0.35985848 ... 0.25623235 0.65716901 0.90069282]
  [0.16164597 0.8993078  0.45872129 ... 0.06143546 0.08794734 0.6305493 ]
  [0.07805567 0.23593489 0.33199285 ... 0.72764435 0.48752432 0.68956195]
  ...
  [0.0092275  0.51381658 0.95269962 ... 0.21493994 0.40446742 0.26658657]
  [0.55952629 0.90247632 0.26416086 ... 0.56797522 0.14240438 0.8523591 ]
  [0.60104123 0.29343011 0.85762449 ... 0.58957983 0.56846697 0.00260711]]

 [[0.97567674 0.70985016 0.11320136 ... 0.03982734 0.99846205 0.35293633]
  [0.47310933 0.42715684 0.28189882 ... 0.74218773 0.31132516 0.29467891]
  [0.03530911 0.63110816 0.74653695 ... 0.21535622 0.74287144 0.80483191]
  ...
  [0.85891195 0.02278325 0.40933757 ... 0.2381746  0.56353551 0.9182542 ]
  [0.73590441 0.97455662 0.73590503 ... 0.08374926 0.34689194 0.74470162]
  [0.38278419 0.1907342  0.23895229 ... 0.82975144 0.59650917 0.19639132]]

 [[0.9765482  0.64222805 0.166004   ... 0.70781581 0.198556

In [64]:
a1=np.arange(10,100,10)
a1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
print('1st ele : ',a1[0])


1st ele :  10


array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [61]:
print('last ele : ',a1[-1])

last ele :  90


In [65]:
print('first 5 eles : ',a1[-5:])


first 5 eles :  [50 60 70 80 90]


In [66]:
print('Alternate ele : ',a1[::2])

Alternate ele :  [10 30 50 70 90]


In [88]:
a12=np.arange(1,101)
a12=np.reshape(a12,(10,10))
a12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [72]:
print('ele at 2nd row 2nd col :',a12[1,1])

ele at 2nd row 2nd col : 12


In [70]:
print(a12[:8,0])

[ 1 11 21 31 41 51 61 71]


In [75]:
print(a12[[0,-1],:])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [84]:
print(a12[[0,-1],4:8])

[[ 5  6  7  8]
 [95 96 97 98]]


In [83]:
print(a12[:3,:3])

[[ 1  2  3]
 [11 12 13]
 [21 22 23]]


In [82]:
print(a12[3:,3:]+1)

[[ 35  36  37  38  39  40  41]
 [ 45  46  47  48  49  50  51]
 [ 55  56  57  58  59  60  61]
 [ 65  66  67  68  69  70  71]
 [ 75  76  77  78  79  80  81]
 [ 85  86  87  88  89  90  91]
 [ 95  96  97  98  99 100 101]]


In [89]:
print(np.unique(a12))

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [90]:
print(np.sort(a12))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [91]:
np.argmax(a1)

8

In [93]:
np.argmin(a1)

0

In [94]:
sh=np.array([2,4,5,3,6])
m=np.array([50,70,80,55,80])
print('cov ',np.cov(sh,m))

cov  [[  2.5   21.25]
 [ 21.25 195.  ]]


In [95]:
np.savetxt('a12_file.csv',a12)

In [97]:
a13=np.loadtxt("a12_file.csv")

In [98]:
np.corrcoef(sh,m)

array([[1.        , 0.96243548],
       [0.96243548, 1.        ]])